### ISSUE TITLE
BrokenExternalLink can be "hacked" - if 3rd party websites return bad response code the report breaks

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-externallinks#61]
Present on version 4.4.1.
* External links to LinkedIn return response with 999 status code - however, this is **not** included in HTTPResponse as a status code.
* This means when the BrokenExternalLinkReport is run, the status code saved in BrokenExternalLink cannot be found and an error is thrown.
* Additionally, it is **not** easy to add response codes to HTTPResponse.
* We suggest checking if the response exists before saving it to BrokenExternalLink; or for HTTPResponse **not** to throw an error, but to respond with "UNKNOWN" instead.

**Comment by robbieaverill** [comment]
Valid HTTP status codes [are 1xx to 5xx](https://tools.ietf.org/html/rfc7231#page-47) - HTTPRequest validates the status codes you give it against a list before it sets it. LinkedIn should not be returning an invalid status code, as far as I can tell the bug is on their end. A quick search looks like if you set a User-Agent in the request then they won't return a 999 response, so perhaps the bug here is that the HTTPRequest object that this module constructs is not extensible enough before it is sent - if it were, you could add the user agent in your project code until a time where their API returns a valid response.

Would you mind me rewording the issue slightly?

**Comment by sunnysideup** [comment]
Because the site is upgraded, the bad code was probably recorded in 3.6... Of course, codes should be "valid", but sometimes they are not and it is not great that the whole report breaks if the code is bad.

**Comment by robbieaverill** [comment]
Yes, I think 2xx respondes should be accepted and maybe 3xx responses too but anything else should be reported as broken

**Comment by sunnysideup** [comment]
I see this totally different. Why would we break our report if a third-party has a bad code? Is that not opening us up to breaking the CMS?  How do CMS users win in this scenario?  We could simply say: "unrecognised response code (999)" and just leave it at that, without breaking the whole report?  This makes it much easier to debug, this means the report is still usable, etc... There will always be dodgy website returning weird response codes.  Lets not make that our problem.

**Comment by robbieaverill** [comment]
Sorry when I say “reported as broken” I mean handled gracefully by this module and reported as a broken link, rather than allowing the report to break entirely

**Comment by sunnysideup** [comment]
Yeah - that sounds perfect.

**Comment by robbieaverill** [comment]
Alright so turns out the logic for this was already there, it's just that the `catch` was missing a namespace import for InvalidArgumentException, meaning it was never caught. I've fixed this and added some tests at #62.

**Comment by NightJar** [comment]
Merged fix.
